repos:
-   repo: local
    hooks:
    -   id: black-jupyter
        files: src/
        args:
          - --line-length=120
        name: black-jupyter
        entry: python -m black --check --diff --color
        language: system
    -   id: mypy
        files: src/
        args:
          - --strict
        name: mypy
        entry: python -m mypy
        language: system