trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements/requirements-tst.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest-azurepipelines
    pytest
  displayName: 'pytest'

- script: |
    mypy ./ --explicit-package-bases
  displayName: 'mypy'

- script: |
    ruff check ./
  displayName: 'ruff'