name: Pull request checks

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-tst.txt
    - name: Check types with mypy
      run: |
        mypy ./ --explicit-package-bases
    - name: Lint with ruff
      run: |
        ruff check ./
    - name: Test with pytest
      run: |
        pytest
